"""The 300-patient synthetic set (I1, §9): 50 vignettes × (English, Hindi, Odia) × (man, woman).

Each patient gets a made-up name and village from the language's region, an age spread over the vignette's range, and
ordinary vital signs for the age with the vignette's own values on top; the danger-sign check is recorded (no signs).
Chronic vignettes are returning patients with one or two earlier visits. Every tenth patient also has an incomplete
copy (vital signs and the danger-sign check left out), for B6. Deterministic: the same seed gives the same file.

Usage: python backend/scripts/make_patients300.py [seed=300] [out=backend/tests/data/patients300.yaml]
"""

import random
import sys
from datetime import date, timedelta
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "backend/tests/data/vignettes300.yaml"
LANGS = ("en", "hi", "or")
NAMES = {
    "or": {"M": ["Bikash Sahu", "Prakash Nayak", "Sudam Behera", "Ramesh Pradhan", "Manoj Das", "Kailash Majhi", "Sanjay Rout", "Debasis Mohanty"],
           "F": ["Sabita Sahu", "Mamata Nayak", "Pramila Behera", "Sasmita Pradhan", "Kuni Das", "Jharana Majhi", "Lipi Rout", "Gitanjali Mohanty"]},
    "hi": {"M": ["Ramesh Yadav", "Suresh Kumar", "Mahesh Prasad", "Rajesh Singh", "Dinesh Paswan", "Anil Gupta", "Mukesh Verma", "Santosh Mishra"],
           "F": ["Sunita Devi", "Geeta Yadav", "Rekha Kumari", "Anita Singh", "Poonam Paswan", "Savitri Gupta", "Meena Verma", "Kiran Mishra"]},
    "en": {"M": ["Arjun Reddy", "Vikram Patil", "Rahul Menon", "Karthik Iyer", "Aditya Joshi", "Imran Shaikh", "Joseph Thomas", "Nikhil Rao"],
           "F": ["Priya Reddy", "Sneha Patil", "Anjali Menon", "Lakshmi Iyer", "Pooja Joshi", "Ayesha Shaikh", "Mary Thomas", "Divya Rao"]},
}
PLACES = {
    "or": [("Manikpur", "Khordha", "Odisha"), ("Baliguda", "Kandhamal", "Odisha"), ("Rengali", "Sambalpur", "Odisha"), ("Kantapada", "Cuttack", "Odisha")],
    "hi": [("Rampur Kalan", "Varanasi", "Uttar Pradesh"), ("Sonbarsa", "Sitamarhi", "Bihar"), ("Khajuri", "Bhopal", "Madhya Pradesh"), ("Barauli", "Gopalganj", "Bihar")],
    "en": [("Hosakote", "Bengaluru Rural", "Karnataka"), ("Shirur", "Pune", "Maharashtra"), ("Kuttanad", "Alappuzha", "Kerala"), ("Kalyani", "Nadia", "West Bengal")],
}
ADULT = {"pulse": 80, "resp_rate": 16, "spo2": 98, "bp_systolic": 120, "bp_diastolic": 80, "temp_f": 98.6, "avpu": "A"}
CHILD = {"pulse": 100, "resp_rate": 24, "spo2": 98, "temp_f": 98.6, "avpu": "A"}
TODAY = date(2026, 10, 8)


def ordinary(age: int, rng: random.Random) -> dict:
    v = dict(ADULT if age >= 12 else CHILD)
    v["pulse"] += rng.randint(-6, 6)
    if age >= 12:
        v["bp_systolic"] += rng.randint(-8, 8)
        v["bp_diastolic"] += rng.randint(-5, 5)
    return v


def main(seed: int = 300, out: str = "backend/tests/data/patients300.yaml") -> None:
    rng = random.Random(seed)
    vign = yaml.safe_load(SRC.read_text(encoding="utf-8"))["vignettes"]
    patients, incomplete = [], []
    for v in vign:
        lo, hi = v["ages"]
        cat = v.get("category", "normal")
        slots = [(lang, sex) for lang in LANGS for sex in (("F", "F") if cat == "maternal" else ("M", "F"))]
        ages = [round(lo + (hi - lo) * k / 5) for k in range(6)]
        rng.shuffle(ages)
        for (lang, sex), age in zip(slots, ages):
            n = len(patients) + 1
            village, district, state = rng.choice(PLACES[lang])
            vitals = {**ordinary(age, rng), **(v.get("vitals") or {})}
            p = {
                "id": f"P{n:03d}", "vignette": v["id"], "expect": v["expect"], "name": rng.choice(NAMES[lang][sex]), "age": age,
                "sex": sex, "language": lang, "village": village, "district": district, "state": state,
                "intake": {"category": cat, "language": lang, "chief_complaint": v["text"][lang], "duration": v.get("duration"),
                           "severity": v.get("severity"), "vitals": vitals, "exam": {"done": True, "signs": [], "by": "Nurse"},
                           **({"maternal": v["maternal"]} if v.get("maternal") else {}),
                           **({"chronic": v["chronic"]} if v.get("chronic") else {})},
            }
            if v.get("returning"):
                p["earlier_visits"] = [{"date": (TODAY - timedelta(days=90 * k + rng.randint(0, 10))).isoformat(),
                                        "vitals": {**ordinary(age, rng), **{k2: x for k2, x in (v.get("vitals") or {}).items() if k2 != "avpu"}}}
                                       for k in range(rng.choice((1, 2)), 0, -1)]
            patients.append(p)
            if n % 10 == 0:
                gap = {**p, "id": p["id"] + "-incomplete", "intake": {**p["intake"], "vitals": None}}
                gap["intake"].pop("exam")
                incomplete.append(gap)
    head = ("# Generated by backend/scripts/make_patients300.py from vignettes300.yaml; synthetic, no patient data.\n"
            "# Names and villages are made up for the region of each language.\n")
    Path(out).write_text(head + yaml.safe_dump({"seed": seed, "patients": patients, "incomplete": incomplete}, allow_unicode=True,
                                               sort_keys=False, width=200), encoding="utf-8")
    print(f"{len(patients)} patients, {sum('earlier_visits' in p for p in patients)} returning, {len(incomplete)} incomplete copies → {out}")


if __name__ == "__main__":
    a = sys.argv[1:]
    main(int(a[0]) if a else 300, a[1] if len(a) > 1 else "backend/tests/data/patients300.yaml")
